# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erequests.proto\"%\n\x07Image2D\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x0c\"Q\n\x07Model3D\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x0c\x12\x1e\n\x07texture\x18\x03 \x01(\x0b\x32\x08.Image2DH\x00\x88\x01\x01\x42\n\n\x08_texture2;\n\x15GarmentReconstruction\x12\"\n\ngetModel3D\x12\x08.Image2D\x1a\x08.Model3D\"\x00\x32\x39\n\x13HumanReconsturction\x12\"\n\ngetModel3D\x12\x08.Image2D\x1a\x08.Model3D\"\x00\x62\x06proto3')



_IMAGE2D = DESCRIPTOR.message_types_by_name['Image2D']
_MODEL3D = DESCRIPTOR.message_types_by_name['Model3D']
Image2D = _reflection.GeneratedProtocolMessageType('Image2D', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE2D,
  '__module__' : 'requests_pb2'
  # @@protoc_insertion_point(class_scope:Image2D)
  })
_sym_db.RegisterMessage(Image2D)

Model3D = _reflection.GeneratedProtocolMessageType('Model3D', (_message.Message,), {
  'DESCRIPTOR' : _MODEL3D,
  '__module__' : 'requests_pb2'
  # @@protoc_insertion_point(class_scope:Model3D)
  })
_sym_db.RegisterMessage(Model3D)

_GARMENTRECONSTRUCTION = DESCRIPTOR.services_by_name['GarmentReconstruction']
_HUMANRECONSTURCTION = DESCRIPTOR.services_by_name['HumanReconsturction']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE2D._serialized_start=18
  _IMAGE2D._serialized_end=55
  _MODEL3D._serialized_start=57
  _MODEL3D._serialized_end=138
  _GARMENTRECONSTRUCTION._serialized_start=140
  _GARMENTRECONSTRUCTION._serialized_end=199
  _HUMANRECONSTURCTION._serialized_start=201
  _HUMANRECONSTURCTION._serialized_end=258
# @@protoc_insertion_point(module_scope)
