# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import requests_pb2 as requests__pb2


class GarmentReconstructionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getModel3D = channel.unary_unary(
                '/GarmentReconstruction/getModel3D',
                request_serializer=requests__pb2.Image2D.SerializeToString,
                response_deserializer=requests__pb2.Model3D.FromString,
                )


class GarmentReconstructionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getModel3D(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GarmentReconstructionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getModel3D': grpc.unary_unary_rpc_method_handler(
                    servicer.getModel3D,
                    request_deserializer=requests__pb2.Image2D.FromString,
                    response_serializer=requests__pb2.Model3D.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GarmentReconstruction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GarmentReconstruction(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getModel3D(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GarmentReconstruction/getModel3D',
            requests__pb2.Image2D.SerializeToString,
            requests__pb2.Model3D.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class HumanReconsturctionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getModel3D = channel.unary_unary(
                '/HumanReconsturction/getModel3D',
                request_serializer=requests__pb2.Image2D.SerializeToString,
                response_deserializer=requests__pb2.Model3D.FromString,
                )


class HumanReconsturctionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getModel3D(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HumanReconsturctionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getModel3D': grpc.unary_unary_rpc_method_handler(
                    servicer.getModel3D,
                    request_deserializer=requests__pb2.Image2D.FromString,
                    response_serializer=requests__pb2.Model3D.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HumanReconsturction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HumanReconsturction(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getModel3D(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HumanReconsturction/getModel3D',
            requests__pb2.Image2D.SerializeToString,
            requests__pb2.Model3D.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
