# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import requests_pb2 as requests__pb2


class GarmentReconstructionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reconstruct = channel.unary_stream(
                '/GarmentReconstruction/reconstruct',
                request_serializer=requests__pb2.GarmentReconstructionRequest.SerializeToString,
                response_deserializer=requests__pb2.Model3D.FromString,
                )


class GarmentReconstructionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reconstruct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GarmentReconstructionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reconstruct': grpc.unary_stream_rpc_method_handler(
                    servicer.reconstruct,
                    request_deserializer=requests__pb2.GarmentReconstructionRequest.FromString,
                    response_serializer=requests__pb2.Model3D.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GarmentReconstruction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GarmentReconstruction(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reconstruct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/GarmentReconstruction/reconstruct',
            requests__pb2.GarmentReconstructionRequest.SerializeToString,
            requests__pb2.Model3D.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class PoseDetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getPose = channel.unary_unary(
                '/PoseDetection/getPose',
                request_serializer=requests__pb2.ByteBuffer.SerializeToString,
                response_deserializer=requests__pb2.FloatMat.FromString,
                )


class PoseDetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoseDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getPose': grpc.unary_unary_rpc_method_handler(
                    servicer.getPose,
                    request_deserializer=requests__pb2.ByteBuffer.FromString,
                    response_serializer=requests__pb2.FloatMat.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PoseDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PoseDetection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PoseDetection/getPose',
            requests__pb2.ByteBuffer.SerializeToString,
            requests__pb2.FloatMat.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
